"""Chip simulation backends (nevresim, SANA-FE, Lava Loihi, TTFS)."""

from mimarsinan.chip_simulation.backend import (
    BACKEND_REGISTRY,
    Backend,
    BackendRegistry,
    SimulationBackend,
)
from mimarsinan.chip_simulation.certification import (
    CertificationCell,
    CertificationFloorBook,
    CertificationStatus,
    CertificationVerdict,
    RegressionFloor,
    certify,
    freeze_cell,
    load_floor_book,
    save_floor_book,
)
from mimarsinan.chip_simulation.cost_extraction import (
    CostRecord,
    CostScatter,
    extract_cost_record,
    extract_cost_record_from_run,
    load_cost_record,
    save_cost_record,
)
from mimarsinan.chip_simulation.coverage_ledger import (
    AXES,
    CoverageReport,
    CoverageStatus,
    HypervolumeAxis,
    HypervolumeCell,
    claimed_subproduct,
    coverage_report,
)
from mimarsinan.chip_simulation.weight_reuse_cost_model import (
    DEFAULT_COEFFICIENT_BAND,
    CoefficientBand,
    CostBand,
    DmaCostCoefficients,
    PhaseCostBreakdown,
    phase_cost_band,
    phase_cost_model,
    vgg16_224_scheduled_cost,
)
from mimarsinan.chip_simulation.recording import spike_modes

__all__ = [
    "spike_modes",
    "Backend",
    "SimulationBackend",
    "BackendRegistry",
    "BACKEND_REGISTRY",
    "CertificationCell",
    "RegressionFloor",
    "CertificationFloorBook",
    "CertificationStatus",
    "CertificationVerdict",
    "certify",
    "freeze_cell",
    "load_floor_book",
    "save_floor_book",
    "CostRecord",
    "CostScatter",
    "extract_cost_record",
    "extract_cost_record_from_run",
    "load_cost_record",
    "save_cost_record",
    "DmaCostCoefficients",
    "CoefficientBand",
    "CostBand",
    "PhaseCostBreakdown",
    "DEFAULT_COEFFICIENT_BAND",
    "phase_cost_model",
    "phase_cost_band",
    "vgg16_224_scheduled_cost",
    "AXES",
    "HypervolumeAxis",
    "HypervolumeCell",
    "CoverageStatus",
    "CoverageReport",
    "coverage_report",
    "claimed_subproduct",
]
