"""Research prototype-to-production harness contracts."""

from mimarsinan.research.harness import (
    ACCEPTANCE_DEPLOYED_ACC,
    ACCEPTANCE_RELATIVE_TIME,
    MIXER_DIAGNOSTIC_STEP_NAMES,
    AcceptanceGate,
    BudgetSchedule,
    DiagnosticCell,
    DiagnosticManifest,
    ExperimentContext,
    FixRecipe,
    MechanismResult,
    MixerBudgetSchedule,
    RecipePreset,
    build_mnist_mixer_manifest,
    VehicleSpec,
    normalize_retention,
    planned_mnist_mixer_ledger_row,
    promotion_record,
    recipe_preset,
    recipe_presets,
    recipe_registry,
)

__all__ = [
    "VehicleSpec",
    "FixRecipe",
    "BudgetSchedule",
    "MixerBudgetSchedule",
    "ExperimentContext",
    "MechanismResult",
    "ACCEPTANCE_DEPLOYED_ACC",
    "ACCEPTANCE_RELATIVE_TIME",
    "MIXER_DIAGNOSTIC_STEP_NAMES",
    "AcceptanceGate",
    "DiagnosticCell",
    "DiagnosticManifest",
    "RecipePreset",
    "build_mnist_mixer_manifest",
    "planned_mnist_mixer_ledger_row",
    "normalize_retention",
    "promotion_record",
    "recipe_presets",
    "recipe_preset",
    "recipe_registry",
]
