"""The committed study prose: docs/odin_fpga_compile_limits_study.md.

Rendered from the record so a number can never drift out of the sentence that
explains it; the fast gate asserts the file on disk equals this rendering.
"""

from __future__ import annotations

from typing import Any, List, Mapping

from mimarsinan.chip_simulation.odin_rtl.limits.configurations import (
    STOCK_KEY,
    WRAPPER_TOP,
)
from mimarsinan.chip_simulation.odin_rtl.limits.readings import (
    memory_cross_check_lines,
    verdict_lines,
    widest_ratio_sentence,
    wrapper_tile_lines,
)
from mimarsinan.chip_simulation.odin_rtl.limits.tables import (
    BRAM36_WORDS,
    COLUMN_TITLES,
    availability_lines,
    bound_lines,
    device_lines,
    measurements_table,
    memory_table,
    ratio_lines,
    row_of,
    rows_of,
    variant_bound_sections,
)


def render_study(record: Mapping[str, Any]) -> str:
    """The committed study; the fast gate asserts the file equals this string."""
    stock = row_of(record, STOCK_KEY)
    overhead = record["wrapper_overhead"]
    slope = record["capture_ram_slope"]
    shipped = row_of(record, overhead["wrapper"])["geometry"]
    ff_per_word = slope["per_capture_word"]["flip_flops"]
    shipped_cap_ffs = int(ff_per_word * shipped["shipped_cap_words"])
    shipped_cap_luts = int(
        slope["per_capture_word"]["lut_equivalent"] * shipped["shipped_cap_words"])
    device = record["device"]
    lines: List[str] = [
        "# ODIN on an FPGA: the compile-limits study",
        "",
        "Plan `docs/odin_firing_semantics_and_rtl_export_plan.md` §8, P8 -- the",
        "SYNTHESIS half. It answers one question with measurements: what does one",
        "ODIN-family core cost in FPGA fabric, and how many of them fit an Alveo",
        "U55C. It answers a second question by refusing to: how many fit *after the",
        "Alveo shell takes its share* is NOT measured here and is not guessed at.",
        "",
        "## Method",
        "",
        f"- Tool: `{record['tool']['version']}`, target family `{record['family']}`",
        "  -- the UltraScale+ family the U55C's XCU55C part belongs to.",
        "- Every configuration goes through the SAME driver as the P5.5a gate",
        "  (`chip_simulation/odin_rtl/synthesis.py`), the same `synth_xilinx` call",
        "  and the same `stat -json` census partition",
        "  (`chip_simulation/odin_rtl/synth_census.py`). Nothing is measured a",
        "  second way, and the exact script of every row is in",
        "  `hw/fpga/compile_limits.json`.",
        "- The GENERATED variants are the ones plan §7 row 20 proves at zero",
        "  difference against their nevresim/torch twins. The study reads them from",
        "  the same catalog the cosimulation gates read",
        "  (`mapping/export/odin_gen/variants.py`), so a geometry cannot be costed",
        "  here unless a cosimulation proved it.",
        f"- The stock 256x256 row is NOT re-measured: it is read from",
        f"  `{stock['measured_by']}`, the P5.5a artifact.",
        f"- Regenerate DELIBERATELY with `scripts/hw_tests/regen_compile_limits.py`;",
        "  the [slow] gate `tests/integration/test_odin_compile_limits.py` re-derives",
        "  every non-stock row and requires an exact match.",
        "",
        "## What was measured",
        "",
        *[f"- `{row['key']}` -- {row['label']}" for row in rows_of(record)],
        "",
        *measurements_table(record),
        "",
        "`bram_tiles` counts a RAMB18E2 as half a tile; the LUT-equivalent column",
        "adds unpacked `INV` cells to `LUT1..LUT6`, exactly as the P5.5a report",
        "does. No configuration emitted a DSP, a URAM, or a single cell the",
        "census could not classify -- every `unclassified` bucket in the record is",
        "empty -- so those two device columns cannot bind and are reported as",
        "`n/a` in every bound below.",
        "",
        "## The memory arithmetic, per configuration",
        "",
        "Every array is sized by the spec that generated it (or, for the stock",
        "core, by the overlay wrapper's declared geometry), so the bits column",
        "below is the RTL's own arithmetic and not a second derivation. The last",
        "column divides those bits by a tile and is a FLOOR only: tiles are",
        "allocated by DEPTH and WIDTH, not by bit count, and the paragraphs that",
        "follow do that arithmetic per array against what was measured.",
        "",
        *memory_table(record),
        "",
        "Cross-checking that against the censuses above:",
        "",
        *memory_cross_check_lines(record),
        "",
        "## How the geometry moves the numbers",
        "",
        "A handful of points do not support a fitted curve, so this section",
        "reports ratios and nothing else.",
        "",
        *ratio_lines(record),
        "",
        "Read against the geometries: the synapse array tracks",
        "axons x neurons x weight_bits and is now paid for in TILES, so it has",
        "left the LUT column -- " + widest_ratio_sentence(record) + " What the",
        "LUT column still carries is the soma datapath (whose width follows",
        "membrane_bits + weight_bits) and the threshold array's distributed RAM,",
        "neither of which grows with the crossbar. The flip-flop column tracks",
        "neurons x membrane_bits plus a fixed control block, so every 256-neuron",
        "16-bit row above carries the same flip-flop count to within two",
        "registers whatever its crossbar does -- 256 axons on a 4-bit cell, 512",
        "on a 4-bit cell and 1,024 on an 8-bit cell span 8x in synapse bits and",
        "8x in tiles at that one flip-flop count and within a few per cent of",
        "one LUT-site count. That is the",
        "measured shape of the relief the WIDE chip configuration buys: the",
        "crossbar is bought in tiles, and tiles are the resource the device has",
        "the most of relative to what a core needs.",
        "",
        "## What the kernel wrapper costs around a core",
        "",
        f"`{WRAPPER_TOP}` at NC=1 was synthesized at two capture depths of the",
        "STOCK fabric, and once more around EACH generated chip configuration --",
        "the same top and the same shipped depths over a different source set,",
        "which is how a chip configuration selects its core. The overhead below",
        f"is derived from the stock pair only, and is {overhead['meaning']}:",
        "",
        "| Column | Wrapper overhead (delta vs the stock core) |",
        "| --- | ---: |",
        *[f"| `{column}` | {overhead['delta'][column]:,.0f} |"
          for column, _ in COLUMN_TITLES],
        f"| `lut_sites` (the bound's LUT class) "
        f"| {overhead['delta_costs']['lut_sites']:,.0f} |",
        "",
        "Both of the wrapper's own RAMs infer block RAM, and the "
        f"{overhead['delta']['bram36']:,.0f} RAMB36E2 of overhead above is exactly "
        "their declared depth:",
        "",
        *wrapper_tile_lines(record, overhead),
        "",
        "Each has ONE synchronous write port and ONE registered read port, which",
        "is what a tile can be. `cap_ram` reaches that shape through a write",
        "arbiter: its two header words (the events the fabric saw, and the cycle",
        "the program ended on) used to be written at fixed addresses from the",
        "sequencer, a third write port that no tile has, and they now go out",
        "through the SAME port as the streaming record, at drain time, when the",
        "streaming writes have stopped.",
        "",
        "`fifo_ram` reaches it the same way, and it is the ELASTIC op-stream",
        "buffer, not a program store. The wrapper used to carry a 262,144x32",
        "`prog_ram` -- a redundant fabric copy of host memory, 256 RAMB36E2",
        "tiles of the device's 2,016 at its shipped depth -- and the routed",
        "U55C build never got them: Vivado put the whole array into distributed",
        "RAM instead, 163,840 LUTs as RAM and 24 BRAM tiles total, none of them",
        "the program. That RAM IS GONE. The op",
        "stream arrives live from the runtime host and passes through this",
        "FIFO, so the wrapper's storage no longer scales with a program's",
        "length at all, and both wrapper points below are measured at the depth",
        "the kernel actually SHIPS with rather than a shrunk stand-in.",
        "",
        f"The two wrapper points differ ONLY in `CAP_WORDS` "
        f"({slope['extra_capture_words']:,} extra words), which makes the capture",
        "RAM's cost a measurement:",
        "",
        *[f"- `{column}`: {slope['per_capture_word'][column]:+.6f} per capture word"
          for column in ("flip_flops", "lut_equivalent", "bram36")],
        "",
        f"A capture word costs {ff_per_word:.0f} flip-flops: it is bought in "
        f"TILES, one RAMB36E2 per "
        f"{1 / slope['per_capture_word']['bram36']:,.0f} words. That is a",
        "REVERSAL of what the previous revision of this study measured -- with",
        "three write ports (the streaming record plus two fixed-address header",
        "writes) the capture RAM could not infer a tile and cost 32 flip-flops",
        "per word, which at any shippable depth exceeded the device's entire",
        "register budget and made the kernel unbuildable as written. The",
        f"wrapper now SHIPS with `CAP_WORDS = {shipped['shipped_cap_words']:,}` "
        f"-- {(shipped['shipped_cap_words'] - 2) // 4:,} event records held in "
        f"{shipped['shipped_cap_words'] // BRAM36_WORDS} tiles and "
        f"{shipped_cap_ffs:,} flip-flops -- and THAT depth is the one measured "
        "above, not a shrunk stand-in for it. NEITHER depth is a stand-in any",
        "more: the census above IS the wrapper this repository ships, so the",
        "wrapper overhead the bounds below reserve needs no extrapolation at",
        "all.",
        "",
        "## The device, with provenance",
        "",
        f"{device['provenance']}",
        "",
        *device_lines(record),
        "",
        "### The number this study does NOT have",
        "",
        f"{device['shell_overhead']}",
        "",
        "## The packing bound",
        "",
        "There is no single headline number, and this section refuses to print",
        "one. The bound is a FUNCTION of which resource you ask about and which",
        "availability you assume:",
        "",
        "```",
        "N_max(resource) = floor( (available(resource) - fixed_overhead(resource))",
        "                         / per_core(resource) )",
        "```",
        "",
        "`available` comes from one of two scenarios, and only the first is",
        "datasheet-grounded:",
        "",
        *availability_lines(record),
        "",
        "`fixed_overhead` is either zero (cores alone, no host interface at all --",
        "not a buildable design, but the cleanest read of the core cost) or the",
        "measured wrapper overhead above.",
        "",
        f"### The stock core (`{STOCK_KEY}`)",
        "",
        "Without any wrapper reserved:",
        "",
        *bound_lines(record, configuration=STOCK_KEY, wrapper_reserved=False),
        "",
        "With the measured wrapper overhead reserved once:",
        "",
        *bound_lines(record, configuration=STOCK_KEY, wrapper_reserved=True),
        "",
        *variant_bound_sections(record),
        "## The verdict",
        "",
        *verdict_lines(record),
        "",
        "## What the BOARD half of P8 still owes",
        "",
        "- **The Vivado utilization report (B0-adjacent).** `v++` link on HACC for",
        "  `xilinx_u55c_gen3x16_xdma_base_3`, then `report_utilization` on the",
        "  implemented design. That single artifact replaces BOTH the shell",
        "  assumption above and the yosys-vs-Vivado mapping caveat below, and it",
        "  is the only thing that can turn these bounds into a claim about a card.",
        "- **Measured fidelity.** The on-board certificate campaign (plan §7 row",
        "  21, R11b): deployed counts against the nevresim twin at zero",
        "  difference, on silicon rather than in a cosimulation.",
        "- **The measured campaign.** Programming and execution walls from the real",
        "  card, which the deployment record's timing fragment already has a place",
        "  for.",
        "- **A Vivado read of the two memory fixes.** The two RTL defects the",
        "  previous revision of this study found -- the capture RAM's three write",
        "  ports and the generated core's asynchronous synapse read -- are FIXED",
        "  in the tree these numbers were measured on, and every number above",
        "  moved because of it. yosys says both memories now infer tiles; only",
        "  Vivado can say the same about the build that goes on the card.",
        "",
        "## The caveat this study must carry",
        "",
        "yosys is not Vivado. Its Xilinx mapping is generic: it emits `CARRY4`",
        "where UltraScale+ has `CARRY8`, leaves `INV` unpacked, does not model LUT",
        "pairing, and chooses distributed RAM by its own heuristics rather than",
        "Vivado's. Every LUT and FF number here is an ORDER-OF-MAGNITUDE budget,",
        "the BRAM counts are the most trustworthy column because tile geometry is",
        "discrete, and nothing here says anything about timing closure, placement,",
        "routing across the three SLRs, or the HBM AXI infrastructure. The bounds",
        "are ceilings on a ceiling.",
        "",
    ]
    return "\n".join(lines)
