"""Registry entries: workload (model/data/pruning/weights) and training keys."""

from __future__ import annotations

from mimarsinan.config_schema.registry.relevance import Relevance as R
from mimarsinan.config_schema.registry.types import (
    Category,
    ConfigKeySchema as _E,
    FieldType as T,
)

_SEARCH_ACTIVE = R.any_of(
    R.when("model_config_mode", in_=("search",)),
    R.when("hw_config_mode", in_=("search",)),
)

ENTRIES = (
    _E("model_config_mode", group="workload", owner="deployment_specs/search_mode",
       type=T.ENUM, options=("user", "search"), category=Category.BASIC, exposure="user",
       label="Model Config Mode",
       doc="user: declare model_type/model_config; search: NAS discovers the architecture."),
    _E("hw_config_mode", group="workload", owner="deployment_specs/search_mode",
       type=T.ENUM, options=("fixed", "search"), category=Category.BASIC, exposure="user",
       label="Hardware Config Mode",
       doc="fixed: declare the core grid; search: hardware co-search discovers it."),
    _E("model_type", group="workload", owner="model_registry/builders",
       type=T.STR, category=Category.BASIC, exposure="user", label="Model Type", important=True,
       doc="Registered model builder id (see /api/model_types).",
       relevant=R.when("model_config_mode", in_=("user",))),
    _E("model_config", group="workload", owner="model_registry/builders",
       type=T.JSON, category=Category.BASIC, exposure="user", label="Model Config",
       doc="Per-builder architecture hyperparameters; the field schema comes from "
           "the builder (see /api/model_config_schema/{model_type}).",
       relevant=R.when("model_config_mode", in_=("user",))),
    _E("model_factory", group="workload", owner="model_registry",
       type=T.STR, category=Category.ADVANCED, label="Model Factory",
       doc="Explicit model factory override (research escape; normally absent)."),
    _E("arch_search", group="workload", owner="search/architecture_search",
       type=T.JSON, category=Category.ADVANCED, exposure="user", label="Architecture Search",
       doc="NAS optimizer, budget, and objective declaration (see /api/wizard/schema).",
       relevant=_SEARCH_ACTIVE),
    _E("preprocessing", group="workload", owner="data_handling/preprocessing",
       type=T.JSON, category=Category.ADVANCED, exposure="user", label="Preprocessing",
       doc="Input preprocessing spec: resize_to, normalize (imagenet/cifar/...), interpolation."),
    _E("pruning", group="workload", owner="pruning_adaptation",
       type=T.BOOL, category=Category.BASIC, exposure="user", label="Pruning Enabled",
       effect="Adds the Pruning Adaptation step", doc="Enable magnitude pruning adaptation."),
    _E("pruning_fraction", group="workload", owner="pruning_adaptation",
       type=T.FLOAT, category=Category.BASIC, exposure="user", label="Pruning Fraction",
       doc="Fraction of weights pruned by the adaptation.", bounds=(0.0, 1.0),
       relevant=R.when_true("pruning")),
    _E("prune_sparsity", group="workload", owner="pruning_adaptation",
       type=T.FLOAT, category=Category.ADVANCED, label="Prune Sparsity",
       doc="Legacy sparsity knob consumed by the pruning tuner mask builder.",
       bounds=(0.0, 1.0), relevant=R.when_true("pruning")),
    _E("weight_source", group="workload", owner="weight_preloading",
       type=T.STR, category=Category.ADVANCED, exposure="user", label="Weight Source",
       doc="Pretrained weight source id/path; presence selects the fine-tune path "
           "(finetune_epochs/finetune_lr) instead of from-scratch pretraining."),
    _E("preload_weights", group="workload", owner="weight_preloading",
       type=T.BOOL, category=Category.ADVANCED, label="Preload Weights",
       doc="Load cached weights when available instead of pretraining."),
    _E("spike_encoding_seed", group="workload", owner="spike_generation",
       type=T.INT, category=Category.ADVANCED, label="Spike Encoding Seed",
       doc="Seed for stochastic spike-train encoding; null follows the run seed."),
    _E("lr", group="training", owner="training_loop",
       type=T.FLOAT, category=Category.BASIC, exposure="user", label="Learning Rate",
       doc="Base learning rate for pretraining and adaptation recovery.",
       bounds=(0.0, 1.0)),
    _E("lr_range_min", group="training", owner="lr_finder",
       type=T.FLOAT, category=Category.ADVANCED, label="LR Range Min",
       doc="Lower bound of the LR-finder sweep.", bounds=(0.0, None)),
    _E("lr_range_max", group="training", owner="lr_finder",
       type=T.FLOAT, category=Category.ADVANCED, label="LR Range Max",
       doc="Upper bound of the LR-finder sweep.", bounds=(0.0, None)),
    _E("training_epochs", group="training", owner="training_loop",
       type=T.INT, category=Category.BASIC, exposure="user", label="Training Epochs",
       doc="From-scratch pretraining epochs.", unit="epochs", bounds=(0, None)),
    _E("finetune_epochs", group="training", owner="weight_preloading",
       type=T.INT, category=Category.ADVANCED, exposure="user", label="Fine-tune Epochs",
       doc="Epochs of fine-tuning after preloading pretrained weights.",
       unit="epochs", bounds=(0, None), relevant=R.when_set("weight_source")),
    _E("finetune_lr", group="training", owner="weight_preloading",
       type=T.FLOAT, category=Category.ADVANCED, exposure="user", label="Fine-tune LR",
       doc="Learning rate for the fine-tune path (defaults to lr when absent).",
       bounds=(0.0, 1.0), relevant=R.when_set("weight_source")),
    _E("batch_size", group="training", owner="DataLoaderFactory",
       type=T.INT, category=Category.BASIC, exposure="user", label="Batch Size",
       doc="Training/eval dataloader batch size.", bounds=(1, None)),
    _E("tuning_batch_size", group="training", owner="DataLoaderFactory",
       type=T.INT, category=Category.ADVANCED, label="Tuning Batch Size",
       doc="Adaptation-tuner dataloader batch size override (large-model cells "
           "shrink it to fit tuning-time memory).", bounds=(1, None)),
    _E("training_recipe", group="training", owner="training_loop",
       type=T.RECIPE, category=Category.ADVANCED, exposure="user", label="Training Recipe",
       doc="Optimizer/scheduler recipe for pretraining (AdamW + cosine + LLRD default)."),
    _E("tuning_recipe", group="training", owner="AdaptationManager",
       type=T.RECIPE, category=Category.ADVANCED, exposure="user", label="Tuning Recipe",
       doc="Optimizer/scheduler recipe for adaptation tuners (no warmup/LLRD default)."),
    _E("kd_ce_alpha", group="training", owner="training_loop/distillation",
       type=T.FLOAT, category=Category.ADVANCED, label="KD CE Alpha",
       doc="Cross-entropy weight in the knowledge-distillation blend loss.",
       bounds=(0.0, 1.0)),
    _E("kd_temperature", group="training", owner="training_loop/distillation",
       type=T.FLOAT, category=Category.ADVANCED, label="KD Temperature",
       doc="Softmax temperature for distillation targets.", bounds=(0.0, None)),
)
