"""nevresim's verbatim pass carry: segment roles, train assembly, publication.

The nevresim twin of ``sanafe/runner/carry.py``: which per-segment binaries take
which role (PRODUCING segments add the SPKTRN define to their record build;
CONSUMING segments compile in SpikeTrain input mode), how a consuming segment's
input train is assembled (host-boundary slices through the SAME encoder twin the
HCM flow deploys, carried slices overwritten verbatim), and how a producing
segment's extracted trains become the ``(N, T, size)`` rasters a later pass
replays. A COLLAPSE run computes no roles and every path stays byte-identical.
"""

from __future__ import annotations

from typing import Dict

import numpy as np

from mimarsinan.chip_simulation.recording._spike_encoding import (
    encode_segment_input,
)
from mimarsinan.chip_simulation.simulation_runner.segment_run import (
    raster_from_spike_trains,
)
from mimarsinan.models.spiking.hybrid.carry import publish_carried_trains


def assemble_carried_input_train(
    stage,
    seg_input: np.ndarray,
    state_buffer_trains: Dict[int, np.ndarray],
    *,
    spike_generation_mode: str,
    T: int,
) -> np.ndarray:
    """``(N, T, size)`` input train for a SpikeTrain-mode segment.

    Host-boundary slices are generated by the SAME encoder twin the HCM flow
    deploys (so the rhythm is bit-identical to what the chip's own generator
    would have produced from the value), then carried slices are overwritten
    VERBATIM with the producing pass's extracted trains.
    """
    if spike_generation_mode == "Stochastic":
        missing = [
            int(sl.node_id) for sl in stage.input_map
            if int(sl.node_id) not in state_buffer_trains
        ]
        if missing:
            raise ValueError(
                f"segment '{stage.name}': verbatim replay under Stochastic "
                f"spike generation needs every input slice carried, but nodes "
                f"{missing} are host boundaries — the chip's RNG cannot be "
                f"reproduced host-side"
            )
    encoded = encode_segment_input(seg_input, T, spike_generation_mode)
    train = np.ascontiguousarray(
        np.transpose(encoded, (0, 2, 1)), dtype=np.float64,
    )
    for sl in stage.input_map:
        carried = state_buffer_trains.get(int(sl.node_id))
        if carried is None:
            continue
        width = min(int(sl.size), carried.shape[-1])
        train[:, :, sl.offset:sl.offset + width] = carried[:, :T, :width]
    return train


def publish_segment_trains(
    stage,
    prepared,
    spike_trains: list,
    input_train: "np.ndarray | None",
    *,
    T: int,
    state_buffer_trains: Dict[int, np.ndarray],
) -> None:
    """Gather a producing segment's SPKTRN trains and publish the carried wires."""
    raster = np.stack([
        raster_from_spike_trains(
            spike_trains[i], prepared.output_sources or [], T,
            None if input_train is None else input_train[i],
        )
        for i in range(len(spike_trains))
    ])
    publish_carried_trains(
        stage, raster, prepared.carried_output_node_ids, state_buffer_trains,
    )
